<?php
// Export Functions

/**
 * Export SOP to HTML
 */
function fn_exports_to_html($sop_id, $company_id = null) {
    // Get SOP with steps
    $sop = fn_sops_get_with_steps($sop_id, $company_id);

    if (!$sop) {
        return ['error' => 'SOP not found'];
    }

    $html = '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>' . htmlspecialchars($sop['title']) . '</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px 20px;
            line-height: 1.6;
            color: #333;
        }
        h1 {
            color: #1a1a1a;
            border-bottom: 3px solid #667eea;
            padding-bottom: 10px;
        }
        .description {
            color: #666;
            font-size: 16px;
            margin-bottom: 30px;
        }
        .step {
            margin-bottom: 30px;
            padding: 20px;
            background: #f8f9fa;
            border-radius: 8px;
            border-left: 4px solid #667eea;
        }
        .step-number {
            font-weight: 700;
            color: #667eea;
            font-size: 14px;
            margin-bottom: 8px;
        }
        .step-description {
            font-size: 16px;
            margin-bottom: 15px;
        }
        .step-screenshot {
            max-width: 100%;
            border-radius: 4px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        .step-url {
            font-size: 13px;
            color: #666;
            margin-top: 10px;
            font-family: monospace;
        }
        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #999;
            font-size: 13px;
        }
    </style>
</head>
<body>
    <h1>' . htmlspecialchars($sop['title']) . '</h1>';

    if ($sop['description']) {
        $html .= '<div class="description">' . nl2br(htmlspecialchars($sop['description'])) . '</div>';
    }

    foreach ($sop['steps'] as $step) {
        $html .= '<div class="step">';
        $html .= '<div class="step-number">Step ' . $step['step_order'] . '</div>';
        $html .= '<div class="step-description">' . nl2br(htmlspecialchars($step['description'])) . '</div>';

        if ($step['screenshot_url']) {
            $html .= '<img src="' . htmlspecialchars($step['screenshot_url']) . '" alt="Step screenshot" class="step-screenshot">';
        }

        if ($step['url']) {
            $html .= '<div class="step-url">URL: ' . htmlspecialchars($step['url']) . '</div>';
        }

        $html .= '</div>';
    }

    $html .= '<div class="footer">Generated by SOP Recorder on ' . date('F j, Y') . '</div>';
    $html .= '</body></html>';

    // Track export
    fn_exports_track($sop_id, 'html', $_SESSION['user_id'] ?? null);

    return ['success' => true, 'content' => $html];
}

/**
 * Export SOP to Markdown
 */
function fn_exports_to_markdown($sop_id, $company_id = null) {
    // Get SOP with steps
    $sop = fn_sops_get_with_steps($sop_id, $company_id);

    if (!$sop) {
        return ['error' => 'SOP not found'];
    }

    $markdown = "# " . $sop['title'] . "\n\n";

    if ($sop['description']) {
        $markdown .= $sop['description'] . "\n\n";
    }

    $markdown .= "---\n\n";

    foreach ($sop['steps'] as $step) {
        $markdown .= "## Step " . $step['step_order'] . "\n\n";
        $markdown .= $step['description'] . "\n\n";

        if ($step['screenshot_url']) {
            $markdown .= "![Step screenshot](" . $step['screenshot_url'] . ")\n\n";
        }

        if ($step['url']) {
            $markdown .= "**URL:** " . $step['url'] . "\n\n";
        }

        $markdown .= "---\n\n";
    }

    $markdown .= "*Generated by SOP Recorder on " . date('F j, Y') . "*\n";

    // Track export
    fn_exports_track($sop_id, 'markdown', $_SESSION['user_id'] ?? null);

    return ['success' => true, 'content' => $markdown];
}

/**
 * Export SOP to JSON
 */
function fn_exports_to_json($sop_id, $company_id = null) {
    // Get SOP with steps
    $sop = fn_sops_get_with_steps($sop_id, $company_id);

    if (!$sop) {
        return ['error' => 'SOP not found'];
    }

    $export_data = [
        'sop' => [
            'id' => $sop['sop_id'],
            'title' => $sop['title'],
            'description' => $sop['description'],
            'created_at' => $sop['created_at'],
            'updated_at' => $sop['updated_at']
        ],
        'steps' => array_map(function($step) {
            return [
                'order' => $step['step_order'],
                'action_type' => $step['action_type'],
                'description' => $step['description'],
                'element_selector' => $step['element_selector'],
                'element_text' => $step['element_text'],
                'screenshot_url' => $step['screenshot_url'],
                'url' => $step['url'],
                'metadata' => $step['metadata'] ? json_decode($step['metadata'], true) : null
            ];
        }, $sop['steps']),
        'exported_at' => date('c')
    ];

    // Track export
    fn_exports_track($sop_id, 'json', $_SESSION['user_id'] ?? null);

    return ['success' => true, 'content' => json_encode($export_data, JSON_PRETTY_PRINT)];
}

/**
 * Export SOP to PDF (using HTML to PDF conversion)
 */
function fn_exports_to_pdf($sop_id, $company_id = null) {
    // First generate HTML
    $html_result = fn_exports_to_html($sop_id, $company_id);

    if (isset($html_result['error'])) {
        return $html_result;
    }

    // Note: Actual PDF generation would require a library like TCPDF or Dompdf
    // For now, return HTML with instructions
    $html = $html_result['content'];

    // Track export
    fn_exports_track($sop_id, 'pdf', $_SESSION['user_id'] ?? null);

    return [
        'success' => true,
        'content' => $html,
        'note' => 'PDF generation requires additional library (TCPDF/Dompdf)'
    ];
}

/**
 * Track export
 */
function fn_exports_track($sop_id, $format, $user_id = null) {
    $query = "
        INSERT INTO sop_exports (
            sop_id,
            format,
            exported_by,
            exported_at
        ) VALUES (?, ?, ?, NOW())
    ";

    fn_core_insert_row_no_redirect($query, [$sop_id, $format, $user_id]);

    // Track usage metric
    $sop = fn_sops_get_by_id($sop_id);
    if ($sop && $sop['company_id']) {
        fn_subscriptions_track_usage($sop['company_id'], 'exports_created');
    }
}

/**
 * Get export history for SOP
 */
function fn_exports_get_history($sop_id, $company_id = null) {
    // Verify access
    $sop = fn_sops_get_by_id($sop_id, $company_id);

    if (!$sop) {
        return [];
    }

    $query = "
        SELECT
            se.*,
            u.name as user_name
        FROM sop_exports se
        LEFT JOIN users u ON se.exported_by = u.user_id
        WHERE se.sop_id = ?
        ORDER BY se.exported_at DESC
        LIMIT 50
    ";

    return fn_core_database_rows($query, [$sop_id]);
}

/**
 * Get export statistics for company
 */
function fn_exports_get_stats($company_id) {
    $query = "
        SELECT
            format,
            COUNT(*) as count
        FROM sop_exports se
        JOIN sops s ON se.sop_id = s.sop_id
        WHERE s.company_id = ?
        GROUP BY format
    ";

    $rows = fn_core_database_rows($query, [$company_id]);

    $stats = [];
    foreach ($rows as $row) {
        $stats[$row['format']] = $row['count'];
    }

    return $stats;
}

/**
 * Generate downloadable file
 */
function fn_exports_download($sop_id, $format, $company_id = null) {
    $sop = fn_sops_get_by_id($sop_id, $company_id);

    if (!$sop) {
        return ['error' => 'SOP not found'];
    }

    // Generate content based on format
    switch ($format) {
        case 'html':
            $result = fn_exports_to_html($sop_id, $company_id);
            $filename = fn_exports_sanitize_filename($sop['title']) . '.html';
            $content_type = 'text/html';
            break;

        case 'markdown':
        case 'md':
            $result = fn_exports_to_markdown($sop_id, $company_id);
            $filename = fn_exports_sanitize_filename($sop['title']) . '.md';
            $content_type = 'text/markdown';
            break;

        case 'json':
            $result = fn_exports_to_json($sop_id, $company_id);
            $filename = fn_exports_sanitize_filename($sop['title']) . '.json';
            $content_type = 'application/json';
            break;

        default:
            return ['error' => 'Unsupported format'];
    }

    if (isset($result['error'])) {
        return $result;
    }

    return [
        'success' => true,
        'content' => $result['content'],
        'filename' => $filename,
        'content_type' => $content_type
    ];
}

/**
 * Sanitize filename
 */
function fn_exports_sanitize_filename($filename) {
    // Remove special characters
    $filename = preg_replace('/[^a-zA-Z0-9\-_\s]/', '', $filename);

    // Replace spaces with underscores
    $filename = str_replace(' ', '_', $filename);

    // Limit length
    $filename = substr($filename, 0, 100);

    return $filename ?: 'sop';
}
